### ISSUE TITLE
Implement Authentication

### ISSUE THREAD

**Issue by benkantor** [rit-sse/rapdev2015-api#1]
We need to implement session based authentication. To do this the following needs to be accomplished:
- Implement the /api/login endpoint

This endpoint should authenticate a user given a username and password. If the credentials are correct a session token for the user should be created, stored in redis, and returned to the client. If the credentials are incorrect an unauthorized response should be returned.
- Implement the /api/register endpoint

This endpoint should create a new user, log that user in and return a session storage token. The username and email address should be checked for uniqueness.
- Implement the /api/logout endpoint

This endpoint should logout the user and clear that user's session token.

**Comment by weswigham** [comment]
Session storage is handled by the client persisting the token it receives from the /token endpoint now. Logging out is as simple as deleting the token, logging in (or registering) is a matter of requesting a token from /token (by providing an authentication provider and a token (and any other info we require)). This keeps our API stateless.

**Comment by weswigham** [comment]
As such, this is (though changed) implemented.
