### ISSUE TITLE
Basic Event Querying

### ISSUE THREAD

**Issue by benkantor** [rit-sse/rapdev2015-api#2]
The goal of this issue is to establish the basic event querying. To complete this issue the following should be accomplished:
- Implement the /api/events endpoint 

GET - Return all events for a user
POST - Create an event for a user
- Implement the /api/events/{id} endpoint

GET - Return information for the event whose {id} is specified in the endpoint
PUT - Edit information for the event whose {id} is specified in the endpoint
DEL - Delete the event whose {id} is specified in the endpoint

**Comment by JRJurman** [comment]
Implemented in merge https://github.com/rit-sse/rapdev2015-api/pull/18
